name: "Hongxuan Zhang"
description: "张鸿轩"
baseurl: ""
url: "https://zhang.hongxuan.me"

permalink: /:year/:month/:day/:title/
paginate: 10

gems: [jekyll-paginate]
exclude: ['Sync.sh', 'README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']


# Links
links:
  - title: "About"
    url: /about
  - title: "Research"
    url: /research
  - title: "Experience"
    url: /experience
  - title: "Publication"
    url: /publication
